services:
  stockfill:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stockfill.rule=Host(`stockfill.lan.ddnsgeek.com`)"
      - "traefik.http.routers.stockfill.entrypoints=websecure"
      - "traefik.http.routers.stockfill.tls=true"
      - "traefik.http.routers.stockfill.tls.certresolver=myresolver"
      - "traefik.http.services.stockfill.loadbalancer.server.port=80"
      - "traefik.http.routers.stockfill.middlewares=error-pages-middleware"
      - "io.portainer.accesscontrol.public"

    networks:
#      - proxy
      - traefik_reverse_proxy

networks:
  traefik_reverse_proxy:
    external: true
